services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    depends_on:
      - db
    entrypoint:
      - "./wait-for-it.sh"
      - "db:5432"
      - "--"
      - "python"
      - "fetch_data.py"
    environment:
      API_KEY:     ${API_KEY}
      DB_HOST:     ${DB_HOST}
      DB_PORT:     ${DB_PORT}
      DB_NAME:     ${DB_NAME}
      DB_USER:     ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  dashboard:
    build: .
    depends_on:
      - app
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "python", "dashboard.py"]
    ports:
      - "8050:8050"
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT:     ${DB_PORT}
        DB_NAME:     ${DB_NAME}
        DB_USER:     ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}